# Example parse_config.yaml
# User can customize which metrics, tenants, and rounds to include in the analysis
selected_metrics:
  - cpu_usage
  - memory_usage
selected_tenants:
  - tenant-a
  - tenant-b
  - tenant-c
  - tenant-d
selected_rounds:
  - round-1
data_root: /home/phil/Projects/nn-analysis/demo-data  # Caminho absoluto para os dados de entrada
processed_data_dir: /home/phil/Projects/nn-analysis/data/processed  # Caminho absoluto para saída dos dados processados
