# Configuração do Pipeline de Análise Multi-Tenant

# Diretórios de entrada/saída
data_root: /home/phil/Projects/k8s-noisy-analysis/demo-data
experiment_folder: demo-experiment-1-round
processed_data_dir: /home/phil/Projects/k8s-noisy-analysis/data/processed/demo_exp_1_round
output_dir: /home/phil/Projects/k8s-noisy-analysis/outputs/demo-experiment-1-round

# Configuração de ingestão de dados
output_parquet_name: /home/phil/Projects/k8s-noisy-analysis/data/processed/demo_exp_1_round.parquet
# Usar um arquivo parquet existente diretamente
input_parquet_path: /home/phil/Projects/k8s-noisy-analysis/data/processed/demo_exp_1_round.parquet

# Seleção de dados
selected_metrics:
  - cpu_usage
  - memory_usage
  - disk_io_total
  - network_total_bandwidth
  
selected_tenants:
  - tenant-a
  - tenant-b
  - tenant-c
  - tenant-d
  
selected_rounds:
  - round-1

# Parâmetros de análise
correlation:
  methods:
    - pearson
    - spearman
  
causality:
  granger_max_lag: 5
  granger_threshold: 0.05
  transfer_entropy_bins: 8
  
# Opções de visualização
plots:
  figure_size: [10, 6]
  style: tableau-colorblind10
  dpi: 300
