# Configuração do Pipeline de Análise para SFI2 Paper

# Diretórios de entrada/saída
data_root: ./data/sfi2-paper
processed_data_dir: ./data/processed
output_dir: ./outputs/sfi2-paper-analysis

# Configuração de ingestão de dados
output_parquet_name: sfi2_paper.parquet

# Seleção de dados
selected_metrics:
  - cpu_usage
  - memory_usage
  - network_total_bandwidth
  - disk_throughput_total
  
selected_tenants:
  - tenant-cpu
  - tenant-mem
  - tenant-dsk
  - tenant-ntk
  - tenant-nsy
  
selected_rounds:
  - round-1
  - round-2
  - round-3

selected_phases:
  - "1 - Baseline"
  - "2 - CPU Noise"
  - "3 - Memory Noise"
  - "4 - Network Noise"
  - "5 - Disk Noise"
  - "6 - Combined Noise"
  - "7 - Recovery"

# Parâmetros de análise
correlation:
  methods:
    - pearson
    - spearman
  # Novo parâmetro para threshold de correlação  
  threshold: 0.3  # Reduzido de 0.5 para capturar mais correlações
  
causality:
  granger_max_lag: 5
  granger_threshold: 0.05
  transfer_entropy_bins: 8

# Parâmetros de visualização
visualization:
  plot_quality: "high"  # high, medium, low - afeta o DPI e tamanho
  fonts:
    family: "sans-serif"  # Use "sans-serif" para evitar warnings com "serif"
    size: 12
    title_size: 14
  metric_display_names:
    cpu_usage: "CPU Usage (%)"
    memory_usage: "Memory Usage (MB)"
    network_total_bandwidth: "Network Bandwidth (Mbps)"
    disk_throughput_total: "Disk Throughput (MB/s)"
  correlation_graph:
    threshold: 0.3     # Threshold para gráficos de correlação
  causality_graph:
    threshold: 0.05    # Threshold para gráficos de causalidade
  heatmap:
    cmap: "coolwarm"   # Mapa de cores para heatmaps
  boxplot:
    notch: true        # Usar boxplots com notch
  time_series:
    line_width: 1.5    # Espessura das linhas em gráficos de série temporal
  
# Configuração para análise multi-round
multi_round_analysis:
  effect_size:
    methods: ["cohen_d", "eta_squared"]
    baseline_phase: "1 - Baseline"
  meta_analysis:
    p_value_combination: "fisher"  # ou "stouffer"
    confidence_level: 0.95
    alpha: 0.05
  correlation:
    method: "pearson"  # ou "spearman", "kendall"
    min_periods: 3
    min_stable_rounds: 2  # Mínimo de rounds para considerar uma correlação estável
    significance_threshold: 0.5  # Limiar de correlação significativa
  performance:
    use_cache: true
    parallel_processing: false
    gpu_acceleration: false    # Habilitar aceleração por GPU
    gpu_memory_limit: 0.8      # Limite de uso de memória GPU (0.0-1.0)
    large_dataset_threshold: 10000  # Número de linhas para considerar grande dataset
  visualization:
    heatmap_colormap: "RdBu_r"
    show_significance_markers: true
    effect_size_thresholds:
      small: 0.2
      medium: 0.5
      large: 0.8
  
# Opções de visualização
plots:
  figure_size: [10, 6]
  style: tableau-colorblind10
  dpi: 100
